### ISSUE TITLE
Update and document CSM colors

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/IncrementalInference.jl#1007]
- `preUpSolve`
    - `MARGINALIZED` - blue
    - `INITIALIZED` but waiting for children to finish up - brown  

- `initUp` green
    - someInit ? darkgreen : lightgreen  

- `tryDownInit` olive
    - someInit ? seagreen : khaki  

- `solveUp` red
    - isCliqFullDim ? pink : tomato1  

- `solveDown` maroon  

- `updateFromSubgraph`
    - finished lightblue  

- `ERROR_STATUS` red

**Comment by Affie** [comment]
Hi @dehann, see the colours as I have it currently. I'll add to the wiki if it is ok with you?

**Comment by dehann** [comment]
https://juliarobotics.org/Caesar.jl/latest/principles/bayestreePrinciples/#Bayes-Tree-Legend-(from-IIF)

**Comment by dehann** [comment]
sure, think it's fine.
