### ISSUE TITLE
Document how to use CF data in factor evaluation

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/IncrementalInference.jl#1044]
taking over from #783 

xref #467

**Comment by dehann** [comment]
```julia
function (cf::CalcFactor<:LinearRelative})(res, z, x1, x2)
  # cf.metadata
  #  ...
end
```

**Comment by dehann** [comment]
Minimum docs here: https://juliarobotics.org/Caesar.jl/latest/examples/basic_definingfactors/#Metadata

**Comment by Affie** [comment]
FMD is deprecated. So we should document replacements is calcfactor

**Comment by dehann** [comment]
I've added quite a bit of documentation to the types CCW and CalcFactor which should already help a lot.  Still worth adding a bit to Caesar docs on own factors just for quicker learning curve.
