### ISSUE TITLE
"deconvolution tools via differential factors" test fail on julia1.6-beta

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/IncrementalInference.jl#1123]
deconvolution tools via differential factors: Test Failed at /home/runner/work/IncrementalInference.jl/IncrementalInference.jl/test/testDefaultDeconv.jl:100
  Expression: issetequal(ls(tfg), [:x2, :x4, :x6])
Stacktrace:
 [1] macro expansion
   @ ~/work/IncrementalInference.jl/IncrementalInference.jl/test/testDefaultDeconv.jl:100 [inlined]
 [2] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:1152 [inlined]
 [3] top-level scope
   @ ~/work/IncrementalInference.jl/IncrementalInference.jl/test/testDefaultDeconv.jl:84
Test Summary:                                | Pass  Fail  Total
deconvolution tools via differential factors |    2     1      3

**Comment by dehann** [comment]
figured this out, it's a change in variable elimination order between 1.5 and 1.6.  Will PR with fix soon that just forces the `solveTree!(..., eliminationOrder=<same as in 1.5>...)`.
