### ISSUE TITLE
Change AbstractRelativeMinimize in-place residual not return cost

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/IncrementalInference.jl#1124]
needed first before we can close #467

**Comment by Affie** [comment]
There might be a few that needs changing from non-parametric to fit in with parametric.
For example:
https://github.com/JuliaRobotics/RoME.jl/blob/83f9b2f8b3cd60219c00370439024bc04166e40c/src/factors/BearingRange2D.jl#L46-L69

**Comment by dehann** [comment]
note this approach was quickly made obsolete, both Roots and Minimize now return the residual vector
