### ISSUE TITLE
Restore API for `getMsgUpTx(cliq)`

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/IncrementalInference.jl#1174]
Hi @Affie ,

Could you perhaps re-add functions for getting the latest up (similar for down) message from a clique please.  The usage used to be:
```julia
fg = ...
tree, _, = solveTree!(fg);

# the msg sent up from cliq[:x1] to the parent
upmsg = getMsgUpTx(getClique(tree, :x1))
```

Looks like all those functions were removed during #459.  The idea would be that we can manually inspect and/or can use with `solveCliq!` for debugging.

Thanks,
Dehann

**Comment by Affie** [comment]
Will these work? I added, but it felt unnecessary so commented it out. 
I’ll just re add and and make sure DownRx is populated. 

https://github.com/JuliaRobotics/IncrementalInference.jl/blob/a2ef785854b2b29b4b22b745d9ce21e1ea2f7ea4/src/TreeMessageAccessors.jl#L120-L132

**Comment by dehann** [comment]
Hi Johan, yes the commented out ones look like the right thing:
https://github.com/JuliaRobotics/IncrementalInference.jl/blob/a2ef785854b2b29b4b22b745d9ce21e1ea2f7ea4/src/TreeMessageAccessors.jl#L131

Also see RP 155 liked just above

**Comment by dehann** [comment]
should also add them to the tests so that we can make sure the API for messages on the tree remains available.
