### ISSUE TITLE
CCW.threadmodel for a factor is not persisted with save/loadfg

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/IncrementalInference.jl#1194]
Just noting it here, probably part of CCW, CPT, FMd, CF CFM make-over.

**Comment by dehann** [comment]
Perhaps we should rather make this part of the factor definition and more permanent if we able to confirm computational benefits from memory etc?

Think user should still have "backdoor" access to disable multithreading in case there is some kind of debugging required, or desire to test otherwise.

**Comment by dehann** [comment]
threadmodel was removed from CCW and is now obsolete, so no point in storing it.
