### ISSUE TITLE
filepath functionality for bayes tree too

### ISSUE THREAD

**Issue by mc2922** [JuliaRobotics/IncrementalInference.jl#125]
same as writegraphpdf for bayes tree or keyword argument to give wipeBuildNewTree a filepath? 

re #118

**Comment by dehann** [comment]
see [code lines here](https://github.com/JuliaRobotics/IncrementalInference.jl/blob/4ebdcb62ff4c530002f62fc2f4515c2441b43b5c/src/JunctionTree.jl#L185)
