### ISSUE TITLE
test regression, solveTree! :parametric w/ Manifolds.jl

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/IncrementalInference.jl#1289]
New `vnd.val::Vector{P}` where `P <: Vector{<:Real}` DOES work with `solveGraphParametric!` but ...
 a new hangup on tree message passing version which does not work after test suppressed in d7b0cfe, see:
https://github.com/JuliaRobotics/IncrementalInference.jl/blob/d7b0cfe983afe4955034e020e30d7cc9783ef2fa/test/testBasicParametric.jl#L94-L96

Also see previous suppressed test (unrelated, but related xref #1219 ):
https://github.com/JuliaRobotics/IncrementalInference.jl/blob/d7b0cfe983afe4955034e020e30d7cc9783ef2fa/test/testBasicParametric.jl#L157-L162

cc @Affie

**Comment by Affie** [comment]
First part is fixed
