### ISSUE TITLE
Basic on-manifold example with `Sphere(2)` and one prior fail

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/IncrementalInference.jl#1293]
I've copied the example out to a test, I'm not entirely sure if I'm doing it correctly though.

https://github.com/JuliaRobotics/IncrementalInference.jl/blob/6f1d9491cadd56e3b12ebba71ba2d3e74745ea7c/test/testSphereMani.jl#L1-L46

The same example previously errored as in: #1284

Edit: updated to the latest commit

**Comment by dehann** [comment]
I think this part will definitely cause problems:
```julia
Base.convert(::Type{<:Tuple}, M::Sphere{2, ℝ}) = (:Euclid, :Euclid, :Euclid) 
Base.convert(::Type{<:Tuple}, ::IIF.InstanceType{Sphere{2, ℝ}})  = (:Euclid, :Euclid, :Euclid) 
```

Also not sure if this mean is working properly, since the manifold information is lost, and these are definitely not a standard Euclidean mean:
```julia
@test all(isapprox.(mean(vnd.val), [1,0,0], atol=0.1)) 
```

This mean is something much close to:
https://manoptjl.org/stable/tutorials/MeanAndMedian.html#The-given-Dataset-1

**Comment by Affie** [comment]
I fixed the 3 x Euclid in the next commit of that branch. It should just be 2x. 
I’ll update the first post

**Comment by Affie** [comment]
> Also not sure if this mean is working properly, since the manifold information is lost, and these are definitely not a standard Euclidean mean

The covariance is very small, so it will be very close to 1.0 and the tolerance is 0.1.

**Comment by Affie** [comment]
I just remembered you said AMP is still based on the identity element. So Sphere(2) won't work for now.

**Comment by Affie** [comment]
https://github.com/JuliaRobotics/ApproxManifoldProducts.jl/pull/94 fixes the dimension error.
