### ISSUE TITLE
Sphere(2) variable with a prior gives wrong numerical result

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/IncrementalInference.jl#1298]
We suspect AMP is not ready for Sphere(2) yet
Captured in a test so long:
https://github.com/JuliaRobotics/IncrementalInference.jl/blob/03a5773e061015237e1aa1c2fb02c2cd232c4232/test/testSphereMani.jl#L32-L33

**Comment by Affie** [comment]
See temporary fix in test: https://github.com/JuliaRobotics/IncrementalInference.jl/blob/3cb9b2c36657abe24685ef70d741018e8e2abffe/test/testSphereMani.jl#L12-L13

Can only be properly fixed after AMP#41

**Comment by dehann** [comment]
oh wow, we must remove that pirate from KDE
