### ISSUE TITLE
calcFactorResidualTemporary doc and function does not agree

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/IncrementalInference.jl#1332]
https://github.com/JuliaRobotics/IncrementalInference.jl/blob/db7ff84225cc848c325e57b5fb9d0d85cb6c79b8/src/CalcFactor.jl#L92-L135

https://github.com/JuliaRobotics/IncrementalInference.jl/blob/db7ff84225cc848c325e57b5fb9d0d85cb6c79b8/src/Deprecated.jl#L60

**Comment by dehann** [comment]
from call, intention now on arg order is:
```julia
a_function(fctTyp, varTypes, measurement, varParams)
```

**Comment by dehann** [comment]
Fixed by #1333
