### ISSUE TITLE
Why is `ensureAllInitialized` slow?

### ISSUE THREAD

**Issue by pvazteixeira** [JuliaRobotics/IncrementalInference.jl#135]
[`ensureAllInitialized`](https://github.com/JuliaRobotics/IncrementalInference.jl/blob/a44a082c497bea0c7a5ff5ee7fc8d6264c1af78c/src/FactorGraph01.jl#L517) iterates over all nodes, and takes >1 second/node.

**Comment by pvazteixeira** [comment]
For around 200 nodes: 255.704965 seconds (1.77 G allocations: 92.691 GiB, 13.29% gc time)

**Comment by dehann** [comment]
moved to new minor version v0.6.0 for when when branch `featre/treeinitorder` is merged

**Comment by dehann** [comment]
similarly resolved as #229
