### ISSUE TITLE
Upgrade to RealCircleGroup

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/IncrementalInference.jl#1365]
Circular is not currently working and tests are skipped until we upgrade to `CircleGroup`.

@dehann, we need https://github.com/JuliaManifolds/Manifolds.jl/issues/415 to continue.

**Comment by dehann** [comment]
I'm nervous on timing for v0.25.0 release, so punting to v0.25.1 the `P isa isbitstype` issue `DFG.VND.val::Vector{P}` (which drives this CircleGroup issue).  We will assume this preknow issue as a 'bug' for IIF v0.25.0 and continue work for isbitstypes as further (non-breaking) upgrades in IIF v0.25.x

**Comment by Affie** [comment]
I changed it to the RealCircleGroup in #1389
