### ISSUE TITLE
Ensure tree construction code is only compiled once,

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/IncrementalInference.jl#1513]
Compiling should not repeat each time the graph changes and a new tree is constructed.  First reported in:
- JuliaRobotics/Caesar.jl#835

**Comment by Affie** [comment]
> Compiling should not repeat each time the graph changes and a new tree is constructed

We have a trade-off between compile and run time. I am seeing the long compile times in parametric as well. I suspect it has something to do with factors as even `addFactor` takes long.

**Comment by dehann** [comment]
Clearly some bug or quirk here that's worth figuring out.

I wonder if it has something to do with current attempts to compute numerical gradients for factors in ccw.
