### ISSUE TITLE
Remove CPT (should be replaced by CalcFactor)

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/IncrementalInference.jl#1562]
First doing #1563

**Comment by Affie** [comment]
Some progress here: CPT is removed with tests passing up to `testMultithreaded`.
Should we skip multithreaded factor evaluation for the PR and do it seperately?

**Comment by dehann** [comment]
skip the test as the current latest won't support multithreading.  next versions of IIF will bring threadings back,
