### ISSUE TITLE
Does multihypo NamedTuple recipe dynamic dispatch?

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/IncrementalInference.jl#1566]
Oh, btw, think the same thing might be happening with multihypo recipes:
https://github.com/JuliaRobotics/IncrementalInference.jl/blob/40962b76cc03c55b49bfded871a7db60f0a0fd22/src/ExplicitDiscreteMarginalizations.jl#L227

_Originally posted by @dehann in https://github.com/JuliaRobotics/IncrementalInference.jl/issues/1564#issuecomment-1185633151_

**Comment by dehann** [comment]
Probably best to just change this to a hard type.

**Comment by Affie** [comment]
Should also probably fix:

https://github.com/JuliaRobotics/IncrementalInference.jl/blob/40962b76cc03c55b49bfded871a7db60f0a0fd22/src/services/EvalFactor.jl#L155-L157

**Comment by Affie** [comment]
and:
https://github.com/JuliaRobotics/IncrementalInference.jl/blob/40962b76cc03c55b49bfded871a7db60f0a0fd22/src/services/EvalFactor.jl#L235-L237

**Comment by Affie** [comment]
> (;certainidx, allelements, activehypo, mhidx) 

That should actually be fine.

**Comment by dehann** [comment]
> Yes I agree. The bad case is if the names are variable. 

So is this fine to use with good performance?
```julia
struct MyType1{T <: NamedTuple}
  x::T
end
```

**Comment by Affie** [comment]
It will be a tradeoff between compile time and runtime. Every new NamedTuple will require a new method to be compiled.

**Comment by Affie** [comment]
This tip is relevant here: https://docs.julialang.org/en/v1/manual/performance-tips/#The-dangers-of-abusing-multiple-dispatch-(aka,-more-on-types-with-values-as-parameters)

**Comment by dehann** [comment]
Agreed, thanks.

**Comment by dehann** [comment]
Changed this to a hard type `HypoRecipe` anyway:
- #1669
