### ISSUE TITLE
Allow for more flexible node names

### ISSUE THREAD

**Issue by pvazteixeira** [JuliaRobotics/IncrementalInference.jl#165]
Some node labels are longer than a single letter and number.  For example maybe one can add node labels:
```julia
:x1
:s1
:p2
:offset3
:cal10_3
:pt100_1
```

**Comment by pvazteixeira** [comment]
just for reference: the same assumption is made "downstream" in [RoME/src/RobotUtils.jl:574](https://github.com/JuliaRobotics/RoME.jl/blob/10715715c7a03c5a2c1615317fe87f9b4f1da582/src/RobotUtils.jl#L574)

**Comment by dehann** [comment]
cc @Affie

**Comment by dehann** [comment]
xref GearsAD/GraffSDK.jl#98

**Comment by dehann** [comment]
recently used `:t1` and the code worked.  The utility functions like `ls(fg)` will not work yet, but progress is being made.

**Comment by dehann** [comment]
will be provided by DFG, see here:
https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/fcd5247a73b5432543afb63b9d567cb03edfc31f/src/services/GraphsDFG.jl#L231

**Comment by dehann** [comment]
done
