### ISSUE TITLE
num_edges(fg.g) = 0 when loading from jld2

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/IncrementalInference.jl#174]
Possibly losing information or not reconstructing the `FactorGraph` object  when loading from jld2 file.

**Comment by GearsAD** [comment]
Is this related to softtype issue?

**Comment by dehann** [comment]
will be made obsolete when JuliaRobotics/DistributedFactorGraphs.jl#35 is resolved

**Comment by dehann** [comment]
use DistributedFactorGraphs.saveDFG or loadDFG instead.
