### ISSUE TITLE
Feature Request: Solver Progress

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/IncrementalInference.jl#224]
Is it possible to get the approximate solver progress.

**Comment by dehann** [comment]
new state machine based solver will make this quite easy to do.  Should happen in v0.6.x

**Comment by dehann** [comment]
see #273

**Comment by dehann** [comment]
we can just count how many clique state machines have completed for progress bar.

**Comment by dehann** [comment]
Partially addressed via human interpretation of #349
