### ISSUE TITLE
one function needs maxparallel in FactorGraph01.jl

### ISSUE THREAD

**Issue by mc2922** [JuliaRobotics/IncrementalInference.jl#345]
https://github.com/JuliaRobotics/IncrementalInference.jl/blob/cb43f2f2b2203b7efa962c72904043a207afd6fa/src/FactorGraph01.jl#L888
rmVarFromMarg needs maxparallel variable passed in? 
for addFactor on line: 
https://github.com/JuliaRobotics/IncrementalInference.jl/blob/cb43f2f2b2203b7efa962c72904043a207afd6fa/src/FactorGraph01.jl#L902

@dehann

**Comment by dehann** [comment]
okay thanks will do
