### ISSUE TITLE
Support LightDFG for solving

### ISSUE THREAD

**Issue by GearsAD** [JuliaRobotics/IncrementalInference.jl#368]
REF: https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/pull/67

**Comment by Affie** [comment]
@GearsAD it looks like it runs a lot deeper, I'll need to complete a course in IIF to fix.

got this so far to init with the same type :-)
```julia
#init an empty fg with a provided type
function initfg(fgtype::DataType;
                 sessionname="NA",
                 robotname="",
                 username="",
                 cloudgraph=nothing)::AbstractDFG

  fgtype <: AbstractDFG || @error "wrong type argument for initfg()"

  return fgtype(params=SolverParams())
end
```

in the mean time, this seems to fix it for now https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/pull/73

**Comment by dehann** [comment]
Take this as lecture 1, intro into IIF

**Comment by dehann** [comment]
related to #364
