### ISSUE TITLE
Change convention to PPE from MAP

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/IncrementalInference.jl#381]
Change to PosteriorParametricEstimate (PPE) rather than existing "MAP_Est" which meant maximum a posteriori.

**Comment by GearsAD** [comment]
WIP is on branch: https://github.com/JuliaRobotics/IncrementalInference.jl/tree/feature/3Q19/addingppe

**Comment by dehann** [comment]
xref JuliaRobotics/DistributedFactorGraphs.jl#147
