### ISSUE TITLE
Need to populate PPE in solver data with a PPE estimate

### ISSUE THREAD

**Issue by GearsAD** [JuliaRobotics/IncrementalInference.jl#398]
Replace this with a call to generate a PPE from the KDE: https://github.com/JuliaRobotics/IncrementalInference.jl/blob/feature/3Q19/addingppe/src/CliqStateMachineUtils.jl#L649-L650

**Comment by dehann** [comment]
by PPE do you actually mean "modefit"?  I meant PPE as Parametric Point Estimates which includes mean, max, and modefit...

**Comment by dehann** [comment]
intended to use:
https://github.com/dehann/IteratedProbabilisticClassification.jl

can move to JuliaRobotics also

**Comment by GearsAD** [comment]
During discus sions we spoke about replacing MAP estimate with an EM-based estimate, I guess I called that PPE and inserted it into the estimate results dictionary as `:ppe`. We can change it to `:modefit`, whichever you think is best.

**Comment by dehann** [comment]
PPE is properly populated since v0.10.0
