### ISSUE TITLE
Should we move InMemoryDFGTypes to DFG

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/IncrementalInference.jl#402]
Also, maybe rename to IIFInMemoryDFGTypes?
It is IIF specific, but will cause breaking changes if types is changes or removed. There were talks of removing MetaGraphsDFG
Perhaps just until DFG stabilizes.

**Comment by dehann** [comment]
I don't mind moving `InMemory` definition to DFG.

**Comment by Affie** [comment]
Looks like we missed this one. Was suppose to go with new DFG tag with removal of Meta and Symbol graphs exports to prevent breaking IIF. 
Can one still update before tag is registered?

**Comment by Affie** [comment]
MetaGraphsDFG and SymbolDFG  use in IIF is ok, don't think it is in use at other places yet.
