### ISSUE TITLE
Provide LightGraphs alternative to Graphs.jl and remove as default.

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/IncrementalInference.jl#456]
Graphs.jl is hard to use, slow, in julia attic, and not fully functional.
We need two parts to replace: 
- Factor Graphs, related #364 
  - [x] alternative - LightDFG
  - [x] evaluate
  - [x] swap
- BayesTree, related #365
  - [ ] alternative using LightGraphs.jl/MetaGraphs.jl see #558 
  - [ ] evaluate
  - [ ] swap

**Comment by dehann** [comment]
Acknowledge and agree that we should start looking at swapping.

**Comment by Affie** [comment]
Should we maybe change IIF master `InMemDFGType` to light graphs to start with the evaluation?

**Comment by dehann** [comment]
Tree aspect separated andmoved to #609
