### ISSUE TITLE
Confirm clique sub-graphs only use priors once 

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/IncrementalInference.jl#458]
### The tree
![image](https://user-images.githubusercontent.com/6612981/69703737-c7e89b80-10fa-11ea-8914-96dd1b4083ea.png)

### fg_built, see `l0f1`
![image](https://user-images.githubusercontent.com/6612981/69703347-db473700-10f9-11ea-9e6e-530d73c7ff0b.png)

### fg_beforeupsolve look like it is used
![image](https://user-images.githubusercontent.com/6612981/69703329-d1bdcf00-10f9-11ea-8633-50e96c2f3650.png)

**Comment by dehann** [comment]
yes this is a bug, the `:l0f1` should only occur once.  have to double check if it should first occurrence or frontals only.  The hard part is how do this for initialization.

**Comment by Affie** [comment]
By the same logic: Should all factors not only be used once? On frontals.
see `x3lm3f1`
Note, I'm only looking at subgraphs fg_beforeupsolve (message priors included) so don't know what else the code might do.
**Tree**
![image](https://user-images.githubusercontent.com/6612981/70305478-2f929b00-180d-11ea-9c0f-2d6d1104a1ff.png)
**Clique 1 - x3,lm0,lm3,x1**
![image](https://user-images.githubusercontent.com/6612981/70305258-a5e2cd80-180c-11ea-99c7-662d6bd73852.png)

**Clique 2 - x2: x1,x3,lm3**
![image](https://user-images.githubusercontent.com/6612981/70305435-0c67eb80-180d-11ea-99e4-958582faaf95.png)

**Comment by Affie** [comment]
just copying here for now:
```julia
# create subgraph with no factors on/between seperators
function buildSubgraphFromLabels!(dfg::AbstractDFG,
                                  cliqSubFg::AbstractDFG,
                                  frontals::Vector{Symbol},
                                  separators::Vector{Symbol};
                                  solvable::Int=0)

  for sym in separators
    DFG.addVariable!(cliqSubFg, deepcopy(DFG.getVariable(dfg, sym)))
  end

  addfac = Symbol[]
  for sym in frontals
    DFG.addVariable!(cliqSubFg, deepcopy(DFG.getVariable(dfg, sym)))
    append!(addfac, getNeighbors(dfg,sym))
  end

  allvars = ls(cliqSubFg)
  for sym in addfac
    fac = DFG.getFactor(dfg, sym)
    vos = fac._variableOrderSymbols
    if !exists(cliqSubFg,fac) && vos ⊆ allvars   #TODO don't add duplicates to start with
      DFG.addFactor!(cliqSubFg, fac._variableOrderSymbols, fac)
    end
  end

  # remove orphans if any are there by mistake
  for fct in DFG.getFactors(cliqSubFg)
    # delete any neighboring factors first
    if length(getNeighbors(cliqSubFg, fct)) != length(fct._variableOrderSymbols)
      DFG.deleteFactor!(cliqSubFg, fc)
      @error "deleteFactor! this should not happen"
    end
  end

  return cliqSubFg
end
```

**Comment by dehann** [comment]
Hi @Affie , thanks two things:
- trying to consolidate the now three different buildsubgraph functions is been bit of a lift, and we still have the three separate functions, although they are together in DFG v0.5.2 now.  For future, work I'd request to please help look at how we can drop the 3 build sub graph functions down to just one common function.
- The examples in this issue is great thanks, although I do not have access to the factor graphs you used to make them.  Could you perhaps indicate what the original factor graphs look like please?

**Comment by dehann** [comment]
attempt to recreate the first:
```julia
using IncrementalInference

fg = initfg()

addVariable!(fg, :x0, ContinuousScalar)
```

**Comment by dehann** [comment]
As suggested by @Affie , factors on separators should not be added.

**Comment by dehann** [comment]
Ensuring that we properly resolve Ex2
