### ISSUE TITLE
Can you solve multiple orphaned graphs?

### ISSUE THREAD

**Issue by keevindoherty** [JuliaRobotics/IncrementalInference.jl#518]
For example, a sequence of poses joined by factors and a separate landmark with a prior.

**Comment by Affie** [comment]
One bug is related to `buildCliquePotentials`. It starts from clique 1 and follows children. So an orphaned tree section does not have its potentials build. 
Looking for all the roots `isRoot(tree, cliqId)` and then traversing the tree from all cliqId (and not 1) fixes this.

**Comment by dehann** [comment]
Right, that makes sense thanks for pushing the fix up too!

**Comment by dehann** [comment]
Note for later readers, this issues was transferred over from Caesar.jl, and is now fixed with PR #519
