### ISSUE TITLE
TreeClique index field and underlining graphs structure indexes

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/IncrementalInference.jl#540]
### The `TreeClique` `index` field
```julia
mutable struct TreeClique
  index::Int  
  label::Symbol 
  data::Any
  attributes::Dict{String, Any} #The drawing attributes
end
```
#### Incrementally building new trees with clique reuse needs:
- remove clique method (DF agree)
- unique identifier for clique (DF agree, needs to be unique within a USER/ROBOT/SESSION)

Also useful for future distributed trees (cloud) based corresponding concept in DFG.

#### LightGraphs.jl as replacement for Graphs.jl
- For efficiency, vectors of Integers are used for adjacency.  We can extend it and write our own structure but then we have to maintain it separately.
  - DF, I'm apposed to having to maintain more stuff at this point in time.
- the Integers do not maintain any order but stored in a vector.
    - so iteration is easy clIds, ie 1:getNumCliqs(tree)
 
#### Indexes 
There are two places where an `index` / `key` / `id` is needed:
- the `TreeClique` structure
    - To uniquely identify the clique within USER/ROBOT/SESSION
    - _label in DFG_
- the BayesTree structure itself
    - A key value pair, or index to a value, with the value a `TreeClique` 
      - DF, assuming you referring to cliques here, as in `index/key/id => clique container`

#### `index` field
- useful as an unique identifier such as a counter or an autogenerated GUID.
- do not use this `index` field directly as graph index (what is graph index?) as it complicates keeping the this index in sync with the graph (Bayes Tree)
    - can use getIndex(clique::TreeClique) **maybe good way to deprecate**.
      - DF Don't quite understand what you mean here?
- the corresponding concept in DFG is the label that is unique within a graph.
- we should probably rename (`index`) it to avoid confusion. `cliqId`/`id`?

#### Plan is that:
- Integer indexes always refer to the index in the underlying graph.
- `cliq.index` or rather `cliq.id`/`cliq.cliqId` is a unique id within a tree.
  - DF, since I'm confused, yes that would be good idea -- but hold up, way too many things are changing at the same time.  Not quite sure what you working on at the moment -- hence: 

However, cliq.index is very deeply embedded in CSM.
  - Why is this a problem -- I'm a bit confused sorry?
  - a quick search for '.index' gives 235 results, it is also used directly as an index, so CSM will break if you remove a clique.
The alternative would be to keep the index field updated (mostly applicable to clique removals) (which index field where - _the only index field, the field named index in TreeClique_ , and updated (when? _at removals mostly_), but then another field is needed to uniquely identify a clique (you will be changing the index all the time so its not unique any more, you would need a new unique id).

#### Proposed way forward:
- [x] first merge parametric since its basically implemented there.
- [ ] deprecating with getIndex(clique::TreeClique) seems like the easiest way to get rid of all the `cliq.index` calls
  - DF, sounds reasonable
- [ ] replace direct access based on `cliq.index` calls with graph index.
  - DF, please clarify this a little more -- I don't follow what you mean here unfortunately?
  - The easiest way to see it is with a DFG analogy: current cliq.index <-> factor.label, a graph with cliques.index 1,2,3 can end up as 1,3 if you delete clique.index 2. So in places where iterators are used `i=1:numofCliques(tree)`, you would get 1,2 and 2 was deleted and should point to 3. With light graphs if clique 2 is deleted, clique 3 is put in its place. therefore 1->cliq1, 2->cliq3. As with DFG we can keep track of this in a dictionary.   
- [ ] add `deleteClique` methods

**Comment by dehann** [comment]
ping, see edits above

**Comment by Affie** [comment]
Consider using https://github.com/matbesancon/VertexSafeGraphs.jl as a quick replacement for Graphs.jl.

**Comment by dehann** [comment]
Don't think we should do a quick replacement, let's pick a sensible one and do that as we are able.  Graphs.jl is archived, so its not going anywhere (there won't be breaking changes :-).

**Comment by dehann** [comment]
xref #609
