### ISSUE TITLE
Clique label field and label attribute is a bit confusing with getter/setter. 

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/IncrementalInference.jl#551]
https://github.com/JuliaRobotics/IncrementalInference.jl/blob/c6ad54287a9a2ad849498390601f45e142b098d8/src/JunctionTreeTypes.jl#L29-L34

**Comment by dehann** [comment]
I think this was a result of two "musts":
- Graphs.ExVertex has `.label` -- used for unique ID for code, while
- GraphViz support in Graphs.jl expects `attributes["label"]` -- used for printing frontals and separators for humans

**Comment by Affie** [comment]
> Graphs.ExVertex has .label -- used for unique ID for code, while

I think only `.index` is needed.

**Comment by dehann** [comment]
Think this will get sorted out as part of deprecating Graphs.jl based `::BayesTree`.  Removed from CSM message and belief consolidation list.

**Comment by dehann** [comment]
I think this was resolved with new `CliqueId{T}` approach.  @Affie can confirm?
