### ISSUE TITLE
[Standardization] Can we deprecate labels field in softtype

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/IncrementalInference.jl#580]
From find in project in IIF and RoME the use of the `labels` field in softtypes looks to be duplicated functionality of DFG `tags` 

- Do we need it separate?
- The name is misleading with `label` now revering to the unique id such as :x1, :x2

Its not important now, just a note to future self.

**Comment by dehann** [comment]
Yes please remove softtype.labels entirely

**Comment by Affie** [comment]
Cool. Its been bugging me for a while

**Comment by Affie** [comment]
To be removed:
- [ ] IIF
- [ ] RoME
- [ ] Caesar docs

**Comment by dehann** [comment]
Okay, we going to need IIF v0.9.0 before we can merge JuliaRobotics/RoME.jl#238
