### ISSUE TITLE
Define factors as <:Real

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/IncrementalInference.jl#595]
Helps with Optim.jl requirements too:
- [x] <:Real
- [x] AbstractArray AbstractVector

**Comment by Affie** [comment]
> I think for forward differentiation, we might just need to make small changes. One of the requirements is *The target function must be written generically enough to accept numbers of type `T&lt;:Real` as input (or arrays of these numbers)*
<sub>[View in Slack](https://caesarjl.slack.com/archives/CKGRFPZT8/p1581945186063900)</sub>

**Comment by Affie** [comment]
Also `AbstractVector` or `AbstractArray` to use views instead of making copies.
Automatic forward differentiation then also works.
Should bring a performance improvement too.
