### ISSUE TITLE
Tree init regression in buildup to DFG v0.6 IIF v0.9

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/IncrementalInference.jl#602]
RoME `testBeehive2D_CliqByCliq.jl` started failing on a treeinit test.  Avoided by reverting to graph init, but definitely needs to be resolved.

**Comment by dehann** [comment]
looks like numerical performance is lost even though tree is solving.

**Comment by dehann** [comment]
also see #621

**Comment by dehann** [comment]
Tree init sequencing might be failing.  In one solve of hex example it looked like cliques 2, 5, 6 were still busy with down init when cliques 1, 3, 4 finished down solving (this is based on looking at the color legend of the tree visualization while solving).

**Comment by Affie** [comment]
Issue can be resolved with getSolverParams(fg).useMsgLikelihoods=true and take

**Comment by dehann** [comment]
Thanks good to know thanks, slowing getting stuff resolved!

**Comment by dehann** [comment]
suspect DFG v0.10.7, IIF v0.17.0, and RoME v0.10.0

**Comment by Affie** [comment]
Update RoME tests to use  getSolverParams(fg).useMsgLikelihoods=true and IIF v0.17

**Comment by Affie** [comment]
Test restored in https://github.com/JuliaRobotics/RoME.jl/pull/343
