### ISSUE TITLE
ERROR: UndefVarError: getCliqPotentials not defined

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/IncrementalInference.jl#678]
https://github.com/JuliaRobotics/IncrementalInference.jl/blob/7c03d00d40281f64db074340adcd44df26031b3c/src/JunctionTree.jl#L908-L914

**Comment by dehann** [comment]
Right, we are actually going to deprecate `Cliq` towards more complete `Clique` (as per current verbNouns).

**Comment by dehann** [comment]
not quite sure of the use case here ... I added a similar function and may need to modify further in the future.
