### ISSUE TITLE
Additional requirements

### ISSUE THREAD

**Issue by GearsAD** [JuliaRobotics/IncrementalInference.jl#72]
Need to add these to the required installs:
sudo apt-get install libfontconfig1
sudo apt-get install gettext
sudo apt-get install libcairo2
sudo apt-get install libpango1.0-0

**Comment by dehann** [comment]
These are part of the plotting libraries which have since been separated into [RoMEPlotting](JuliaRobotics/RoMEPlotting.jl) package.
