### ISSUE TITLE
verb `list` a `Vector` or a `Set`

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/IncrementalInference.jl#727]
Currently there are cases of both and not seen a strictly a problem, since Julia itself allows various return types based on dispatch.

- DF, my inclination is to allow both `::AbstractSet` and `::AbstractVector` as response from any verb `list*`.

**Comment by dehann** [comment]
HI @Affie did you have any thoughts on this?

**Comment by Affie** [comment]
I think julia promotes it so it doesn’t matter.
