### ISSUE TITLE
Undo CliqStatus back to an enum

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/IncrementalInference.jl#744]
Had to make it ::Symbol like older mm CSM, as part of #459 consolidation effort

**Comment by dehann** [comment]
make sure `printHistoryLine` preserves the status name and not just an Int.

**Comment by Affie** [comment]
FIY:
```julia
julia> @enum CliqStatus NULL INITIALIZED UPSOLVED MARGINALIZED DOWNSOLVED UPRECYCLED ERROR_STATUS

julia> st = ERROR_STATUS
ERROR_STATUS::CliqStatus = 6

julia> println(st);
ERROR_STATUS

julia> @show(st);
st = ERROR_STATUS

julia> display(st);
ERROR_STATUS::CliqStatus = 6
```

**Comment by dehann** [comment]
Sounds good, lets get v0.16.0 out and then add this as a further part in CSM consolidation in v0.17.0?

**Comment by dehann** [comment]
Can also go for v0.18.0 if that is better

**Comment by Affie** [comment]
It shouldn't be too much effort, so we can still target v0.17
