### ISSUE TITLE
Discussion: Pass variables to factor evaluation so that we can use variable data?

### ISSUE THREAD

**Issue by GearsAD** [JuliaRobotics/IncrementalInference.jl#784]
I'd like to use the data from variables in the factor evaluation, e.g. Radar data. I think we should pass down the variables into the factor evaluation, so that I could potentially use smallData or bigData.

--------

DF edit, predominant design discussion over in #783 -- can use this issue once a decision has been made there on how to split manifest and *user-meta-data* requirement.

user desire for more "metadata" in a variable: https://github.com/JuliaRobotics/IncrementalInference.jl/issues/783#issuecomment-660234861 -- i.e additional data format and contents from end user not know at design time.

**Comment by dehann** [comment]
Remember this part too about user desire for more "metadata" in a variable: https://github.com/JuliaRobotics/IncrementalInference.jl/issues/783#issuecomment-660234861

**Comment by dehann** [comment]
moving to v0.15.0 as more realistic.  Hopefully can make 783 decision by v0.14.0

**Comment by dehann** [comment]
resolved with discussion around and following https://github.com/JuliaRobotics/IncrementalInference.jl/issues/783#issuecomment-665080114

**Comment by dehann** [comment]
Punchline is to use the new `CalcFactor` approach, and hopefully stable API defined in v0.21.  See #467 as relatively well linked issue discussion on what the API should be.  All metadata (variables, smalldata, entry=>data, etc.) is available through the `CalcFactor` approach.  This is both during residual factor evaluation and `getSample`.
