### ISSUE TITLE
Towards immutable FactorMetadata(...)

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/IncrementalInference.jl#825]
Its not the main performance issue right now

**Comment by dehann** [comment]
xref #927

**Comment by dehann** [comment]
Can do as part of larger refactor of the internal numerical commutation stack, including CCW, FMd, CPT, CalcFactor

**Comment by dehann** [comment]
don't loose sight of this comment: https://github.com/JuliaRobotics/IncrementalInference.jl/issues/783#issuecomment-665080114

**Comment by Affie** [comment]
I don't think this is relevant anymore?

**Comment by dehann** [comment]
all consolidated in ccw either during v0.31 or v0.32 work.
