### ISSUE TITLE
auto promote ::DateTime to ::ZonedDateTime

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/IncrementalInference.jl#838]
first suggested by folks elsewhere, but to formalize:  we should permanently do automation inside IIF.addVariable! IIF.addFactor! to promote `::DateTime` to `::ZonedDateTime(dt, localzone())`, since the DFG standard requires ISO 8601 ZonedDateTime for all time stamping.

**Comment by Affie** [comment]
There are separate constructors that takes a datetime (and keyword timezone) and converts is already.

**Comment by Affie** [comment]
There were promotion rules the other way around (zoneddatetime to datetime) to help with depreciation. But that is type piracy and was only temporary.

**Comment by Affie** [comment]
Just for reference: 
https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/ff27aa4b8550f7ac3990aaeb0436062767378b82/src/entities/DFGVariable.jl#L269-L273

https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/ff27aa4b8550f7ac3990aaeb0436062767378b82/src/services/CommonAccessors.jl#L73

**Comment by dehann** [comment]
cool thanks! we should probably make the DFGVariable function use dispatch rather than an if statement, not important to do now though.

**Comment by Affie** [comment]
Jip, good idea. Didn't you want to add it to the `addVariable!` `addFactor!` functions in IIF?
