### ISSUE TITLE
build tree should use `@debug`

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/IncrementalInference.jl#844]
Currently using `@info` which is printing out a little too much when building a new tree (at start of a regular solve).

**Comment by Affie** [comment]
I'm looking at the debug and info messages, should we perhaps make the debugging messages written to file also optional?

**Comment by Affie** [comment]
Didn't know this, you can set the logging level globally with `Logging.disable_logging`

https://docs.julialang.org/en/v1/stdlib/Logging/#Logging.disable_logging
