### ISSUE TITLE
Consolidate btnd.solvableDims into LikelihoodMessage

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/IncrementalInference.jl#910]
https://github.com/JuliaRobotics/IncrementalInference.jl/blob/c7b3c3d91ae586c63d68f51b15e839ef7422cb7b/src/JunctionTreeTypes.jl#L347

**Comment by dehann** [comment]
Okay, so logging how to solve this one.  Each sibling has a possible solvableDim per variable in the clique.  

The rule of thumb here is that if the solve were to occur one sibling at a time, then the last sibling would have the most information available to resolve its estimates;  simultaneously, the first sibling (and intermediate ones) may or may not have the required information from priors yet propagated to that part of the factor graph (from any prior and through measurement functions).

Given the current level of solved-ness of each variable (during init) some cliques are further away from being solved than others.  This information needs to be communicated to each sibling somehow, so that the best order of precedence in various situations can be resolved.  This communication should happen according to tree construction and messages passed along the edges only.

**Comment by dehann** [comment]
The old update call is:
```julia
sdims = getCliqVariableMoreInitDims(csmc.cliqSubFg, csmc.cliq)
updateCliqSolvableDims!(csmc.cliq, sdims, csmc.logger)
```

**Comment by Affie** [comment]
I'm still not completely following with `solvableDims`
Say we work with hex but with priors on x3 and x5 on this tree:
![image](https://user-images.githubusercontent.com/6612981/95227785-d1ed2780-07fe-11eb-9728-d91b3a8477a4.png)

5 and 6 can both do an upinit, why can't they go at the same time?
They have x4 in common so is the information not best mixed in the parent (2)?

**Comment by dehann** [comment]
still wip to get the new code to act the same.

**Comment by dehann** [comment]
Hi @Affie , check out the previous discussion in #344

**Comment by dehann** [comment]
not going to make this 

> at the same

and parking sibling cascade order in #954 (old fetch model).
