### ISSUE TITLE
Consolidate CSM down msg functions

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/IncrementalInference.jl#938]
After #937 consolidate these into a single function:
- `putBeliefMessageDown!`
- `putDwnMsgConsolidated!`
- `prepPutCliqueStatusMsgDwn!`
- `notifyCliqDownInitStatus!`
- `dwnPrepOutMsg`

These are all in the file `src/TreeMsgDwnConsolidation.jl`

using IIF and RoME tests should be sufficient validate things are working.

PS, also feeds into the overall #855

**Comment by Affie** [comment]
#957 is the last part of the fetch functions.

The remaining 2: 
- `putBeliefMessageDown!`
- `putDwnMsgConsolidated!`
Is part of fetch vs take!, issue #855
