### ISSUE TITLE
Should isCliqMarginalizedFromVars be deprecated

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/IncrementalInference.jl#962]
`isCliqMarginalizedFromVars` is either deprecated or bug should be fixed.
It is a similar function to `areCliqVariablesAllMarginalized` but with a bug `getCliqVars` that should probably be `getCliqAllVarIds`
https://github.com/JuliaRobotics/IncrementalInference.jl/blob/edfbefc90124c362e2d57c28b7478eb77e792d44/src/CliqStateMachineUtils.jl#L82-L89

@dehann, can I just move to deprecated for removal?

**Comment by dehann** [comment]
Yes, let's moved that to deprecated.
