### ISSUE TITLE
Bug in getCliqVarInitOrderUp

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/IncrementalInference.jl#978]
https://github.com/JuliaRobotics/IncrementalInference.jl/blob/870e518fc7e808b911bcd50682a2f786a793a80b/src/TreeBasedInitialization.jl#L25-L65

`upmsgs` is a `Dict{Int, LikelihoodMessage}` which make `upmsgids` a `Vector{Int}`
while `allids` is a `Vector{Symbol}`

**Comment by dehann** [comment]
not sure i understand the issue?

either way this might also be related to #925

**Comment by Affie** [comment]
Definitely related to #925. We should probably fix this in a patch release for v0.16.2 and might as well go with #925 then.
