### ISSUE TITLE
Bug - Mixture Prior is not an AbstractPrior

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/IncrementalInference.jl#998]
```julia
p = Mixture(Prior, [Normal(1,1),Normal(1,1)], [0.5, 0.5] )
isPrior(p) == fasle
p isa AbstractPrior == false
```

This makes functions such as `lsfPriors(subfg)` not find it.

**Comment by Affie** [comment]
One possible solution is:
DFG
```julia
function isPrior(dfg::AbstractDFG, fc::Symbol)
  fco = getFactor(dfg, fc)
  isPrior(getFactorType(fco))
end

function isPrior(::AbstractPrior)
  return true
end

function isPrior(::AbstractRelative)
  return false
end
```

IIF
```julia
function DistributedFactorGraphs.isPrior(::Mixture{N, F, S, T}) where {N,F,S,T}
  return F <: AbstractPrior
end
```

**Comment by Affie** [comment]
@dehann let me know if this fits in with Mixtures, then I'll update DFG and IIF.

**Comment by dehann** [comment]
thanks looks okay.  Just reaffirming from #1000.  Mixture can be any FunctorInferenceType, ie AbstractPrior or either of the AbstractRelaives.  this looks specific to issue is on AbstractPrior and suggested does not seem to impede AbstractRelative so looks good to me, thanks!
